# Generated by Django 4.1.7 on 2023-03-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, default=2023, null=True, verbose_name='Ano do carro'),
        ),
    ]
