# Generated by Django 4.2.1 on 2023-05-04 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_veiculo_cliente_id_alter_veiculo_marca_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Saida')),
                ('entrada', models.DateTimeField(verbose_name='Hora de Entrada')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Total')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('tabela_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tabela', verbose_name='Veiculo Valor')),
                ('veiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veiculo')),
            ],
            options={
                'verbose_name_plural': 'Rotativos',
            },
        ),
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('tabela_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tabela', verbose_name='Veiculo Valor')),
                ('veiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name_plural': 'Mensalistas',
            },
        ),
    ]
